apiVersion: v1
kind: PersistentVolume
metadata:
  name: crispr-fg-jamboree-data-pv
spec:
  storageClassName: ""
  claimRef:
    name: crispr-fg-jamboree-data-pvc
    namespace: jhub
  capacity:
    storage: 40G
  accessModes:
    - ReadOnlyMany
  gcePersistentDisk:
    pdName: crispr-fg-jamboree-data-pd
    fsType: ext4
