apiVersion: v1
kind: PersistentVolume
metadata:
  name: igvf-jamboree-data-pv
spec:
  storageClassName: ""
  claimRef:
    name: igvf-jamboree-data-pvc
    namespace: jhub
  capacity:
    storage: 40G
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: igvf-jamboree-data-pd
    readOnly: true
    fsType: ext4
