apiVersion: v1
kind: PersistentVolume
metadata:
  name: igvf-jamboree-data-pv
spec:
  storageClassName: ""
  claimRef:
    name: igvf-jamboree-data-pvc
    namespace: jhub
  capacity:
    storage: 100G
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: igvf-jamboree-data-standard-pd
    readOnly: true
    fsType: ext4
