debug:
  enabled: true

proxy:
  secretToken: "XXXXXXXXXXXXXX"
  https:
    enabled: false

scheduling:
  userScheduler:
    enabled: false
  podPriority:
    enabled: true
  userPlaceholder:
    enabled: true
    replicas: 3
  userPods:
    nodeAffinity:
      matchNodePurpose: prefer

singleuser:
  # 32 cores, 64GB for the jamboree
  memory:
    limit: 20G
    guarantee: 1G
    # limit: 68G
    # guarantee: 64G
  cpu:
    limit: 4
    guarantee: 1
    # limit: 34
    # guarantee: 32
  image:
    name: leepc12/test-jupyterhub
    tag: v0.2.0
  storage:
    # boot disk size
    capacity: 100Gi
    # shared data
    extraVolumes:
      - name: crispr-fg-jamboree-data-pv
        persistentVolumeClaim:
          claimName: crispr-fg-jamboree-data-pvc
          storageClass: ""
    extraVolumeMounts:
      - name: crispr-fg-jamboree-data-pv
        mountPath: /mnt/shared
  extraEnv:
    JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"

hub:
  config:
    Authenticator:
      admin_users:
        - idan
        - jin
      allowed_users:
        - user1
        - user2
        - user3
    DummyAuthenticator:
      password: PASSWORDPASSWORD
    JupyterHub:
      authenticator_class: dummy

cull:
  # need to enable later to shutdown idle pods
  enabled: false
  # shutdown if idle longer than (in seconds)
  timeout: 18000
  # ping (in seconds)
  every: 1800
