debug:
  enabled: true

proxy:
  secretToken: TOKEN_HERE
  https:
    enabled: false

scheduling:
  userScheduler:
    enabled: false
  podPriority:
    enabled: true
  userPlaceholder:
    enabled: true
    replicas: 3
  userPods:
    nodeAffinity:
      matchNodePurpose: prefer

singleuser:
  memory:
    limit: 16G
    guarantee: 12G
  cpu:
    limit: 7
    guarantee: 7
  image:
    name: leepc12/igvf-jamboree-2023
    tag: v0.1.0
  storage:
    # boot disk size
    capacity: 100Gi
    # shared data disk
    extraVolumes:
      - name: igvf-jamboree-data-pv
        persistentVolumeClaim:
          claimName: igvf-jamboree-data-pvc
          readOnly: true
          storageClass: ""
    extraVolumeMounts:
      - name: igvf-jamboree-data-pv
        mountPath: /mnt/shared
        readOnly: true
  # defaultUrl: "/lab"
  extraEnv:
    JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"

hub:
  config:
    Authenticator:
      admin_users:
        - leepc12@stanford.edu
        - bioinfolucas@gmail.com
      allowed_users:
        - test1
        - test2
        - test3
        - test4
        - test5
        - test6
        - test7
      DummyAuthenticator:
      password: THIS_IS_A_SHARED_PASSWORD
    JupyterHub:
      authenticator_class: dummy

cull:
  # need to enable later to stop idle pods
  enabled: true
  # shutdown if idle longer than (in seconds)
  timeout: 10800
  # ping (in seconds)
  every: 600
